### PR TITLE
[source nodes][s]: update NonTabularProcessingNode with metadata

### LINKED ISSUE #29: Changes for NonTabularProcessingNode
we've introduced new processor for updating source metadata. see https://github.com/datahq/assembler/issues/93

Need to updated planner appropriately 

## Acceptance Criteria 

* [x] tests are fine 

## Tasks

* [ ] update `output_nodes` (zip) - add `deduplicate_processors`
* [ ] update `node_collectors` - move `NonTabularProcessingNode` before zip
* [ ] update meta for `NonTabularProcessingNode`

### PR DESCRIPTION
**Pull request by zelima**
fixes #29

Align planner with the changes in the assembler.https://github.com/datahq/assembler/issues/93

### CODE REVIEW

**Comment by akariv** [comment]
@zelima I don't really follow the logic of this PR - 
why do we need to copy the functionality of copy_nontabular_resources here? 
why isn't it enough to modify the paths of the resources to make them be stored under 'archive'?
why do we need to deduplicate resource names?

**Comment by zelima** [comment]
@akariv 
> why do we need to copy the functionality of copy_nontabular_resources here?

To explain, first I should say that `NonTabularProcessingNode` is not actually only for non-tabular but for tabular as well and think it should be renamed to `SourceProcessingNode`. https://github.com/datahq/planner/blob/master/planner/nodes/basic_nodes.py#L54

I Need it to be included there cause we need to copy original files as is, and not tidy up by `tabulator` or `dpp`. (For zip or `data get`) Eg:  if you take a look at the source CSV file inside zipped resource, you'll see that first 2 rows of original data is removed https://datahub.io/core/finance-vix/r/finance-vix_zip.zip. So as `NonTabularProcessingNode` does exactly that - copies exactly as is.

If I don't include it I will get the source file from the very first `ProcessingArtefact` from [here](https://github.com/datahq/planner/blob/master/planner/nodes/planner.py#L122) and that one already includes all the `tabulator`/`dpp` related processing steps. So I will end up with the tidy file.

So if I have to do above and include `NonTabularProcessingNode` there that explains your third question

> why do we need to deduplicate resource names?

As both, very first `ProcessingArtefact` (to kick off process) and `NonTabularProcessingNode` name resources identically (original name) we end up with duplicated resources for `dump.to_zip`. For this, I introduced processor to deduplicate them (or we could include both and name one of them `resource-name_source`)

> why isn't it enough to modify the paths of the resources to make them be stored under 'archive'?

Cause to construct `path` we need to know several things:

* where to place = `archive`  - available 
* resource name = `my-resource`  - available
* extension = `.csv` - not availavle 

We can not know format as `ProcessingArtefact` just does not provide that info and can not guess as we do not have a full file name. 

Also besides this, resource descriptor for source files do not include a hash of the file. that we need to be included as later is used by `remove_hash` processor before `dump.to_zip`. To have nice structure inside zip and after `data get`. If resource descriptor does not include hash, we can not remove it later from path (added by `dump_to_s3`)

The processor that set's path, is making that job as well. https://github.com/datahq/assembler/pull/94/files#diff-80d0cbf9909819b8809ff53c59872f82

**Comment by akariv** [comment]
@zelima I understand.
In this case, I think that we should solve this more systematically. This solution, even though it works, feels more like a band-aid on a bigger problem.

I think the way to go here is to duplicate the tabular sources into two resources - one for the original, and one for the processed source. 
We could create a new type `original` instead of `source/nontabular` and modify the NonTabularProcessorNode to handle only these `original`s.  wdyt?

**Comment by zelima** [comment]
@akariv ok so as I understand you are suggesting following:

* Leave the `source/tabular` as was - apply all the processing steps, place in `data/` directory etc...
* get rid of `source/non-tabular` and introduce `original`. And do everything I'm doing in this PR to that resource (except dedupe probably)

This would mean that we end up with the following tree in zip/`data-get`

```
.
├── archive
│   └── my-resource.csv
├── data
│   ├── my-dataset_report.json
│   ├── my-resource.csv
│   ├── my-resource_csv.csv
│   └── my-resource_json.json
├── datapackage.json
└── README.md
```

and the datapackage.json would look something like this:

```
{
  "name": "my-dataset",
  "resources": [
    {
      "name": "my-resource",
      "datahub": {"type": "source/tabular"},
      "path": "data/my-resource.csv",
      ...
    },
    {
      "name": "my-resource",
      "datahub": {"type": "original"},
      "path": "archive/my-resource.csv",
      ...
    },
    ...
  ]
}

```

One question I've got right away is that in most cases this two files will be Identical, as mostly `source/tabular` will not need any processing, is that OK?

**Comment by zelima** [comment]
Closing This in favour of https://github.com/datahq/planner/pull/37

**Pull request closed without merging**
